safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Rishab Goel"
description: "Masters student at IIT Delhi"
baseurl: ""
url: "https://rishabgoel.github.io/" # replace by your site's url
twitter_username: rgoel0112
github_username:  RishabGoel # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Rishab Goel"
address: "Your Street, <br>Your City, Country"
email: "rgoel0112@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
